# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import activity_service_pb2 as api_dot_v1_dot_activity__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/activity_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActivityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListActivities = channel.unary_unary(
                '/memos.api.v1.ActivityService/ListActivities',
                request_serializer=api_dot_v1_dot_activity__service__pb2.ListActivitiesRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_activity__service__pb2.ListActivitiesResponse.FromString,
                _registered_method=True)
        self.GetActivity = channel.unary_unary(
                '/memos.api.v1.ActivityService/GetActivity',
                request_serializer=api_dot_v1_dot_activity__service__pb2.GetActivityRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_activity__service__pb2.Activity.FromString,
                _registered_method=True)


class ActivityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListActivities(self, request, context):
        """ListActivities returns a list of activities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivity(self, request, context):
        """GetActivity returns the activity with the given id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListActivities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActivities,
                    request_deserializer=api_dot_v1_dot_activity__service__pb2.ListActivitiesRequest.FromString,
                    response_serializer=api_dot_v1_dot_activity__service__pb2.ListActivitiesResponse.SerializeToString,
            ),
            'GetActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivity,
                    request_deserializer=api_dot_v1_dot_activity__service__pb2.GetActivityRequest.FromString,
                    response_serializer=api_dot_v1_dot_activity__service__pb2.Activity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.ActivityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.ActivityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActivityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListActivities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.ActivityService/ListActivities',
            api_dot_v1_dot_activity__service__pb2.ListActivitiesRequest.SerializeToString,
            api_dot_v1_dot_activity__service__pb2.ListActivitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.ActivityService/GetActivity',
            api_dot_v1_dot_activity__service__pb2.GetActivityRequest.SerializeToString,
            api_dot_v1_dot_activity__service__pb2.Activity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
