# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import attachment_service_pb2 as api_dot_v1_dot_attachment__service__pb2
from google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/attachment_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttachmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAttachment = channel.unary_unary(
                '/memos.api.v1.AttachmentService/CreateAttachment',
                request_serializer=api_dot_v1_dot_attachment__service__pb2.CreateAttachmentRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_attachment__service__pb2.Attachment.FromString,
                _registered_method=True)
        self.ListAttachments = channel.unary_unary(
                '/memos.api.v1.AttachmentService/ListAttachments',
                request_serializer=api_dot_v1_dot_attachment__service__pb2.ListAttachmentsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_attachment__service__pb2.ListAttachmentsResponse.FromString,
                _registered_method=True)
        self.GetAttachment = channel.unary_unary(
                '/memos.api.v1.AttachmentService/GetAttachment',
                request_serializer=api_dot_v1_dot_attachment__service__pb2.GetAttachmentRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_attachment__service__pb2.Attachment.FromString,
                _registered_method=True)
        self.GetAttachmentBinary = channel.unary_unary(
                '/memos.api.v1.AttachmentService/GetAttachmentBinary',
                request_serializer=api_dot_v1_dot_attachment__service__pb2.GetAttachmentBinaryRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
                _registered_method=True)
        self.UpdateAttachment = channel.unary_unary(
                '/memos.api.v1.AttachmentService/UpdateAttachment',
                request_serializer=api_dot_v1_dot_attachment__service__pb2.UpdateAttachmentRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_attachment__service__pb2.Attachment.FromString,
                _registered_method=True)
        self.DeleteAttachment = channel.unary_unary(
                '/memos.api.v1.AttachmentService/DeleteAttachment',
                request_serializer=api_dot_v1_dot_attachment__service__pb2.DeleteAttachmentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AttachmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAttachment(self, request, context):
        """CreateAttachment creates a new attachment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAttachments(self, request, context):
        """ListAttachments lists all attachments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttachment(self, request, context):
        """GetAttachment returns a attachment by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttachmentBinary(self, request, context):
        """GetAttachmentBinary returns a attachment binary by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAttachment(self, request, context):
        """UpdateAttachment updates a attachment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAttachment(self, request, context):
        """DeleteAttachment deletes a attachment by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttachmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAttachment,
                    request_deserializer=api_dot_v1_dot_attachment__service__pb2.CreateAttachmentRequest.FromString,
                    response_serializer=api_dot_v1_dot_attachment__service__pb2.Attachment.SerializeToString,
            ),
            'ListAttachments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAttachments,
                    request_deserializer=api_dot_v1_dot_attachment__service__pb2.ListAttachmentsRequest.FromString,
                    response_serializer=api_dot_v1_dot_attachment__service__pb2.ListAttachmentsResponse.SerializeToString,
            ),
            'GetAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttachment,
                    request_deserializer=api_dot_v1_dot_attachment__service__pb2.GetAttachmentRequest.FromString,
                    response_serializer=api_dot_v1_dot_attachment__service__pb2.Attachment.SerializeToString,
            ),
            'GetAttachmentBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttachmentBinary,
                    request_deserializer=api_dot_v1_dot_attachment__service__pb2.GetAttachmentBinaryRequest.FromString,
                    response_serializer=google_dot_api_dot_httpbody__pb2.HttpBody.SerializeToString,
            ),
            'UpdateAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAttachment,
                    request_deserializer=api_dot_v1_dot_attachment__service__pb2.UpdateAttachmentRequest.FromString,
                    response_serializer=api_dot_v1_dot_attachment__service__pb2.Attachment.SerializeToString,
            ),
            'DeleteAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAttachment,
                    request_deserializer=api_dot_v1_dot_attachment__service__pb2.DeleteAttachmentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.AttachmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.AttachmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttachmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.AttachmentService/CreateAttachment',
            api_dot_v1_dot_attachment__service__pb2.CreateAttachmentRequest.SerializeToString,
            api_dot_v1_dot_attachment__service__pb2.Attachment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAttachments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.AttachmentService/ListAttachments',
            api_dot_v1_dot_attachment__service__pb2.ListAttachmentsRequest.SerializeToString,
            api_dot_v1_dot_attachment__service__pb2.ListAttachmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.AttachmentService/GetAttachment',
            api_dot_v1_dot_attachment__service__pb2.GetAttachmentRequest.SerializeToString,
            api_dot_v1_dot_attachment__service__pb2.Attachment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttachmentBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.AttachmentService/GetAttachmentBinary',
            api_dot_v1_dot_attachment__service__pb2.GetAttachmentBinaryRequest.SerializeToString,
            google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.AttachmentService/UpdateAttachment',
            api_dot_v1_dot_attachment__service__pb2.UpdateAttachmentRequest.SerializeToString,
            api_dot_v1_dot_attachment__service__pb2.Attachment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.AttachmentService/DeleteAttachment',
            api_dot_v1_dot_attachment__service__pb2.DeleteAttachmentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
