# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/auth_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/v1/auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mcp_memos.api.v1 import user_service_pb2 as api_dot_v1_dot_user__service__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/v1/auth_service.proto\x12\x0cmemos.api.v1\x1a\x19\x61pi/v1/user_service.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n\x18GetCurrentSessionRequest\"s\n\x19GetCurrentSessionResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.memos.api.v1.User\x12\x34\n\x10last_accessed_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xe5\x02\n\x14\x43reateSessionRequest\x12V\n\x14password_credentials\x18\x01 \x01(\x0b\x32\x36.memos.api.v1.CreateSessionRequest.PasswordCredentialsH\x00\x12L\n\x0fsso_credentials\x18\x02 \x01(\x0b\x32\x31.memos.api.v1.CreateSessionRequest.SSOCredentialsH\x00\x1a\x43\n\x13PasswordCredentials\x12\x15\n\x08username\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x15\n\x08password\x18\x02 \x01(\tB\x03\xe0\x41\x02\x1aS\n\x0eSSOCredentials\x12\x13\n\x06idp_id\x18\x01 \x01(\x05\x42\x03\xe0\x41\x02\x12\x11\n\x04\x63ode\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12\x19\n\x0credirect_uri\x18\x03 \x01(\tB\x03\xe0\x41\x02\x42\r\n\x0b\x63redentials\"o\n\x15\x43reateSessionResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.memos.api.v1.User\x12\x34\n\x10last_accessed_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x16\n\x14\x44\x65leteSessionRequest2\x8b\x03\n\x0b\x41uthService\x12\x8b\x01\n\x11GetCurrentSession\x12&.memos.api.v1.GetCurrentSessionRequest\x1a\'.memos.api.v1.GetCurrentSessionResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/auth/sessions/current\x12z\n\rCreateSession\x12\".memos.api.v1.CreateSessionRequest\x1a#.memos.api.v1.CreateSessionResponse\" \x82\xd3\xe4\x93\x02\x1a\"\x15/api/v1/auth/sessions:\x01*\x12r\n\rDeleteSession\x12\".memos.api.v1.DeleteSessionRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1/auth/sessions/currentB\x0cZ\ngen/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\ngen/api/v1'
  _globals['_CREATESESSIONREQUEST_PASSWORDCREDENTIALS'].fields_by_name['username']._loaded_options = None
  _globals['_CREATESESSIONREQUEST_PASSWORDCREDENTIALS'].fields_by_name['username']._serialized_options = b'\340A\002'
  _globals['_CREATESESSIONREQUEST_PASSWORDCREDENTIALS'].fields_by_name['password']._loaded_options = None
  _globals['_CREATESESSIONREQUEST_PASSWORDCREDENTIALS'].fields_by_name['password']._serialized_options = b'\340A\002'
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS'].fields_by_name['idp_id']._loaded_options = None
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS'].fields_by_name['idp_id']._serialized_options = b'\340A\002'
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS'].fields_by_name['code']._loaded_options = None
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS'].fields_by_name['code']._serialized_options = b'\340A\002'
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS'].fields_by_name['redirect_uri']._loaded_options = None
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS'].fields_by_name['redirect_uri']._serialized_options = b'\340A\002'
  _globals['_AUTHSERVICE'].methods_by_name['GetCurrentSession']._loaded_options = None
  _globals['_AUTHSERVICE'].methods_by_name['GetCurrentSession']._serialized_options = b'\202\323\344\223\002\037\022\035/api/v1/auth/sessions/current'
  _globals['_AUTHSERVICE'].methods_by_name['CreateSession']._loaded_options = None
  _globals['_AUTHSERVICE'].methods_by_name['CreateSession']._serialized_options = b'\202\323\344\223\002\032\"\025/api/v1/auth/sessions:\001*'
  _globals['_AUTHSERVICE'].methods_by_name['DeleteSession']._loaded_options = None
  _globals['_AUTHSERVICE'].methods_by_name['DeleteSession']._serialized_options = b'\202\323\344\223\002\037*\035/api/v1/auth/sessions/current'
  _globals['_GETCURRENTSESSIONREQUEST']._serialized_start=195
  _globals['_GETCURRENTSESSIONREQUEST']._serialized_end=221
  _globals['_GETCURRENTSESSIONRESPONSE']._serialized_start=223
  _globals['_GETCURRENTSESSIONRESPONSE']._serialized_end=338
  _globals['_CREATESESSIONREQUEST']._serialized_start=341
  _globals['_CREATESESSIONREQUEST']._serialized_end=698
  _globals['_CREATESESSIONREQUEST_PASSWORDCREDENTIALS']._serialized_start=531
  _globals['_CREATESESSIONREQUEST_PASSWORDCREDENTIALS']._serialized_end=598
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS']._serialized_start=600
  _globals['_CREATESESSIONREQUEST_SSOCREDENTIALS']._serialized_end=683
  _globals['_CREATESESSIONRESPONSE']._serialized_start=700
  _globals['_CREATESESSIONRESPONSE']._serialized_end=811
  _globals['_DELETESESSIONREQUEST']._serialized_start=813
  _globals['_DELETESESSIONREQUEST']._serialized_end=835
  _globals['_AUTHSERVICE']._serialized_start=838
  _globals['_AUTHSERVICE']._serialized_end=1233
# @@protoc_insertion_point(module_scope)
