# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import idp_service_pb2 as api_dot_v1_dot_idp__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/idp_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityProviderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListIdentityProviders = channel.unary_unary(
                '/memos.api.v1.IdentityProviderService/ListIdentityProviders',
                request_serializer=api_dot_v1_dot_idp__service__pb2.ListIdentityProvidersRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_idp__service__pb2.ListIdentityProvidersResponse.FromString,
                _registered_method=True)
        self.GetIdentityProvider = channel.unary_unary(
                '/memos.api.v1.IdentityProviderService/GetIdentityProvider',
                request_serializer=api_dot_v1_dot_idp__service__pb2.GetIdentityProviderRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_idp__service__pb2.IdentityProvider.FromString,
                _registered_method=True)
        self.CreateIdentityProvider = channel.unary_unary(
                '/memos.api.v1.IdentityProviderService/CreateIdentityProvider',
                request_serializer=api_dot_v1_dot_idp__service__pb2.CreateIdentityProviderRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_idp__service__pb2.IdentityProvider.FromString,
                _registered_method=True)
        self.UpdateIdentityProvider = channel.unary_unary(
                '/memos.api.v1.IdentityProviderService/UpdateIdentityProvider',
                request_serializer=api_dot_v1_dot_idp__service__pb2.UpdateIdentityProviderRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_idp__service__pb2.IdentityProvider.FromString,
                _registered_method=True)
        self.DeleteIdentityProvider = channel.unary_unary(
                '/memos.api.v1.IdentityProviderService/DeleteIdentityProvider',
                request_serializer=api_dot_v1_dot_idp__service__pb2.DeleteIdentityProviderRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class IdentityProviderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListIdentityProviders(self, request, context):
        """ListIdentityProviders lists identity providers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdentityProvider(self, request, context):
        """GetIdentityProvider gets an identity provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIdentityProvider(self, request, context):
        """CreateIdentityProvider creates an identity provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIdentityProvider(self, request, context):
        """UpdateIdentityProvider updates an identity provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIdentityProvider(self, request, context):
        """DeleteIdentityProvider deletes an identity provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityProviderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListIdentityProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIdentityProviders,
                    request_deserializer=api_dot_v1_dot_idp__service__pb2.ListIdentityProvidersRequest.FromString,
                    response_serializer=api_dot_v1_dot_idp__service__pb2.ListIdentityProvidersResponse.SerializeToString,
            ),
            'GetIdentityProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentityProvider,
                    request_deserializer=api_dot_v1_dot_idp__service__pb2.GetIdentityProviderRequest.FromString,
                    response_serializer=api_dot_v1_dot_idp__service__pb2.IdentityProvider.SerializeToString,
            ),
            'CreateIdentityProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIdentityProvider,
                    request_deserializer=api_dot_v1_dot_idp__service__pb2.CreateIdentityProviderRequest.FromString,
                    response_serializer=api_dot_v1_dot_idp__service__pb2.IdentityProvider.SerializeToString,
            ),
            'UpdateIdentityProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIdentityProvider,
                    request_deserializer=api_dot_v1_dot_idp__service__pb2.UpdateIdentityProviderRequest.FromString,
                    response_serializer=api_dot_v1_dot_idp__service__pb2.IdentityProvider.SerializeToString,
            ),
            'DeleteIdentityProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIdentityProvider,
                    request_deserializer=api_dot_v1_dot_idp__service__pb2.DeleteIdentityProviderRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.IdentityProviderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.IdentityProviderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityProviderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListIdentityProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.IdentityProviderService/ListIdentityProviders',
            api_dot_v1_dot_idp__service__pb2.ListIdentityProvidersRequest.SerializeToString,
            api_dot_v1_dot_idp__service__pb2.ListIdentityProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdentityProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.IdentityProviderService/GetIdentityProvider',
            api_dot_v1_dot_idp__service__pb2.GetIdentityProviderRequest.SerializeToString,
            api_dot_v1_dot_idp__service__pb2.IdentityProvider.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIdentityProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.IdentityProviderService/CreateIdentityProvider',
            api_dot_v1_dot_idp__service__pb2.CreateIdentityProviderRequest.SerializeToString,
            api_dot_v1_dot_idp__service__pb2.IdentityProvider.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIdentityProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.IdentityProviderService/UpdateIdentityProvider',
            api_dot_v1_dot_idp__service__pb2.UpdateIdentityProviderRequest.SerializeToString,
            api_dot_v1_dot_idp__service__pb2.IdentityProvider.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIdentityProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.IdentityProviderService/DeleteIdentityProvider',
            api_dot_v1_dot_idp__service__pb2.DeleteIdentityProviderRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
