# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import inbox_service_pb2 as api_dot_v1_dot_inbox__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/inbox_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListInboxes = channel.unary_unary(
                '/memos.api.v1.InboxService/ListInboxes',
                request_serializer=api_dot_v1_dot_inbox__service__pb2.ListInboxesRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_inbox__service__pb2.ListInboxesResponse.FromString,
                _registered_method=True)
        self.UpdateInbox = channel.unary_unary(
                '/memos.api.v1.InboxService/UpdateInbox',
                request_serializer=api_dot_v1_dot_inbox__service__pb2.UpdateInboxRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_inbox__service__pb2.Inbox.FromString,
                _registered_method=True)
        self.DeleteInbox = channel.unary_unary(
                '/memos.api.v1.InboxService/DeleteInbox',
                request_serializer=api_dot_v1_dot_inbox__service__pb2.DeleteInboxRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class InboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListInboxes(self, request, context):
        """ListInboxes lists inboxes for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInbox(self, request, context):
        """UpdateInbox updates an inbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInbox(self, request, context):
        """DeleteInbox deletes an inbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListInboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInboxes,
                    request_deserializer=api_dot_v1_dot_inbox__service__pb2.ListInboxesRequest.FromString,
                    response_serializer=api_dot_v1_dot_inbox__service__pb2.ListInboxesResponse.SerializeToString,
            ),
            'UpdateInbox': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInbox,
                    request_deserializer=api_dot_v1_dot_inbox__service__pb2.UpdateInboxRequest.FromString,
                    response_serializer=api_dot_v1_dot_inbox__service__pb2.Inbox.SerializeToString,
            ),
            'DeleteInbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInbox,
                    request_deserializer=api_dot_v1_dot_inbox__service__pb2.DeleteInboxRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.InboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.InboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListInboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.InboxService/ListInboxes',
            api_dot_v1_dot_inbox__service__pb2.ListInboxesRequest.SerializeToString,
            api_dot_v1_dot_inbox__service__pb2.ListInboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.InboxService/UpdateInbox',
            api_dot_v1_dot_inbox__service__pb2.UpdateInboxRequest.SerializeToString,
            api_dot_v1_dot_inbox__service__pb2.Inbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.InboxService/DeleteInbox',
            api_dot_v1_dot_inbox__service__pb2.DeleteInboxRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
