# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import markdown_service_pb2 as api_dot_v1_dot_markdown__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/markdown_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarkdownServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseMarkdown = channel.unary_unary(
                '/memos.api.v1.MarkdownService/ParseMarkdown',
                request_serializer=api_dot_v1_dot_markdown__service__pb2.ParseMarkdownRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_markdown__service__pb2.ParseMarkdownResponse.FromString,
                _registered_method=True)
        self.RestoreMarkdownNodes = channel.unary_unary(
                '/memos.api.v1.MarkdownService/RestoreMarkdownNodes',
                request_serializer=api_dot_v1_dot_markdown__service__pb2.RestoreMarkdownNodesRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_markdown__service__pb2.RestoreMarkdownNodesResponse.FromString,
                _registered_method=True)
        self.StringifyMarkdownNodes = channel.unary_unary(
                '/memos.api.v1.MarkdownService/StringifyMarkdownNodes',
                request_serializer=api_dot_v1_dot_markdown__service__pb2.StringifyMarkdownNodesRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_markdown__service__pb2.StringifyMarkdownNodesResponse.FromString,
                _registered_method=True)
        self.GetLinkMetadata = channel.unary_unary(
                '/memos.api.v1.MarkdownService/GetLinkMetadata',
                request_serializer=api_dot_v1_dot_markdown__service__pb2.GetLinkMetadataRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_markdown__service__pb2.LinkMetadata.FromString,
                _registered_method=True)


class MarkdownServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseMarkdown(self, request, context):
        """ParseMarkdown parses the given markdown content and returns a list of nodes.
        This is a utility method that transforms markdown text into structured nodes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreMarkdownNodes(self, request, context):
        """RestoreMarkdownNodes restores the given nodes to markdown content.
        This is the inverse operation of ParseMarkdown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StringifyMarkdownNodes(self, request, context):
        """StringifyMarkdownNodes stringify the given nodes to plain text content.
        This removes all markdown formatting and returns plain text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinkMetadata(self, request, context):
        """GetLinkMetadata returns metadata for a given link.
        This is useful for generating link previews.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarkdownServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseMarkdown': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseMarkdown,
                    request_deserializer=api_dot_v1_dot_markdown__service__pb2.ParseMarkdownRequest.FromString,
                    response_serializer=api_dot_v1_dot_markdown__service__pb2.ParseMarkdownResponse.SerializeToString,
            ),
            'RestoreMarkdownNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreMarkdownNodes,
                    request_deserializer=api_dot_v1_dot_markdown__service__pb2.RestoreMarkdownNodesRequest.FromString,
                    response_serializer=api_dot_v1_dot_markdown__service__pb2.RestoreMarkdownNodesResponse.SerializeToString,
            ),
            'StringifyMarkdownNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.StringifyMarkdownNodes,
                    request_deserializer=api_dot_v1_dot_markdown__service__pb2.StringifyMarkdownNodesRequest.FromString,
                    response_serializer=api_dot_v1_dot_markdown__service__pb2.StringifyMarkdownNodesResponse.SerializeToString,
            ),
            'GetLinkMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinkMetadata,
                    request_deserializer=api_dot_v1_dot_markdown__service__pb2.GetLinkMetadataRequest.FromString,
                    response_serializer=api_dot_v1_dot_markdown__service__pb2.LinkMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.MarkdownService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.MarkdownService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarkdownService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseMarkdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MarkdownService/ParseMarkdown',
            api_dot_v1_dot_markdown__service__pb2.ParseMarkdownRequest.SerializeToString,
            api_dot_v1_dot_markdown__service__pb2.ParseMarkdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreMarkdownNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MarkdownService/RestoreMarkdownNodes',
            api_dot_v1_dot_markdown__service__pb2.RestoreMarkdownNodesRequest.SerializeToString,
            api_dot_v1_dot_markdown__service__pb2.RestoreMarkdownNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StringifyMarkdownNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MarkdownService/StringifyMarkdownNodes',
            api_dot_v1_dot_markdown__service__pb2.StringifyMarkdownNodesRequest.SerializeToString,
            api_dot_v1_dot_markdown__service__pb2.StringifyMarkdownNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinkMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MarkdownService/GetLinkMetadata',
            api_dot_v1_dot_markdown__service__pb2.GetLinkMetadataRequest.SerializeToString,
            api_dot_v1_dot_markdown__service__pb2.LinkMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
