# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import memo_service_pb2 as api_dot_v1_dot_memo__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/memo_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMemo = channel.unary_unary(
                '/memos.api.v1.MemoService/CreateMemo',
                request_serializer=api_dot_v1_dot_memo__service__pb2.CreateMemoRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.Memo.FromString,
                _registered_method=True)
        self.ListMemos = channel.unary_unary(
                '/memos.api.v1.MemoService/ListMemos',
                request_serializer=api_dot_v1_dot_memo__service__pb2.ListMemosRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemosResponse.FromString,
                _registered_method=True)
        self.GetMemo = channel.unary_unary(
                '/memos.api.v1.MemoService/GetMemo',
                request_serializer=api_dot_v1_dot_memo__service__pb2.GetMemoRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.Memo.FromString,
                _registered_method=True)
        self.UpdateMemo = channel.unary_unary(
                '/memos.api.v1.MemoService/UpdateMemo',
                request_serializer=api_dot_v1_dot_memo__service__pb2.UpdateMemoRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.Memo.FromString,
                _registered_method=True)
        self.DeleteMemo = channel.unary_unary(
                '/memos.api.v1.MemoService/DeleteMemo',
                request_serializer=api_dot_v1_dot_memo__service__pb2.DeleteMemoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RenameMemoTag = channel.unary_unary(
                '/memos.api.v1.MemoService/RenameMemoTag',
                request_serializer=api_dot_v1_dot_memo__service__pb2.RenameMemoTagRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteMemoTag = channel.unary_unary(
                '/memos.api.v1.MemoService/DeleteMemoTag',
                request_serializer=api_dot_v1_dot_memo__service__pb2.DeleteMemoTagRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetMemoAttachments = channel.unary_unary(
                '/memos.api.v1.MemoService/SetMemoAttachments',
                request_serializer=api_dot_v1_dot_memo__service__pb2.SetMemoAttachmentsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListMemoAttachments = channel.unary_unary(
                '/memos.api.v1.MemoService/ListMemoAttachments',
                request_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoAttachmentsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoAttachmentsResponse.FromString,
                _registered_method=True)
        self.SetMemoRelations = channel.unary_unary(
                '/memos.api.v1.MemoService/SetMemoRelations',
                request_serializer=api_dot_v1_dot_memo__service__pb2.SetMemoRelationsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListMemoRelations = channel.unary_unary(
                '/memos.api.v1.MemoService/ListMemoRelations',
                request_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoRelationsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoRelationsResponse.FromString,
                _registered_method=True)
        self.CreateMemoComment = channel.unary_unary(
                '/memos.api.v1.MemoService/CreateMemoComment',
                request_serializer=api_dot_v1_dot_memo__service__pb2.CreateMemoCommentRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.Memo.FromString,
                _registered_method=True)
        self.ListMemoComments = channel.unary_unary(
                '/memos.api.v1.MemoService/ListMemoComments',
                request_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoCommentsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoCommentsResponse.FromString,
                _registered_method=True)
        self.ListMemoReactions = channel.unary_unary(
                '/memos.api.v1.MemoService/ListMemoReactions',
                request_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoReactionsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoReactionsResponse.FromString,
                _registered_method=True)
        self.UpsertMemoReaction = channel.unary_unary(
                '/memos.api.v1.MemoService/UpsertMemoReaction',
                request_serializer=api_dot_v1_dot_memo__service__pb2.UpsertMemoReactionRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_memo__service__pb2.Reaction.FromString,
                _registered_method=True)
        self.DeleteMemoReaction = channel.unary_unary(
                '/memos.api.v1.MemoService/DeleteMemoReaction',
                request_serializer=api_dot_v1_dot_memo__service__pb2.DeleteMemoReactionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MemoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMemo(self, request, context):
        """CreateMemo creates a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemos(self, request, context):
        """ListMemos lists memos with pagination and filter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemo(self, request, context):
        """GetMemo gets a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemo(self, request, context):
        """UpdateMemo updates a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemo(self, request, context):
        """DeleteMemo deletes a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameMemoTag(self, request, context):
        """RenameMemoTag renames a tag for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemoTag(self, request, context):
        """DeleteMemoTag deletes a tag for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMemoAttachments(self, request, context):
        """SetMemoAttachments sets attachments for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemoAttachments(self, request, context):
        """ListMemoAttachments lists attachments for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMemoRelations(self, request, context):
        """SetMemoRelations sets relations for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemoRelations(self, request, context):
        """ListMemoRelations lists relations for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMemoComment(self, request, context):
        """CreateMemoComment creates a comment for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemoComments(self, request, context):
        """ListMemoComments lists comments for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemoReactions(self, request, context):
        """ListMemoReactions lists reactions for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertMemoReaction(self, request, context):
        """UpsertMemoReaction upserts a reaction for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemoReaction(self, request, context):
        """DeleteMemoReaction deletes a reaction for a memo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMemo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMemo,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.CreateMemoRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.Memo.SerializeToString,
            ),
            'ListMemos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemos,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemosRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.ListMemosResponse.SerializeToString,
            ),
            'GetMemo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemo,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.GetMemoRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.Memo.SerializeToString,
            ),
            'UpdateMemo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemo,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.UpdateMemoRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.Memo.SerializeToString,
            ),
            'DeleteMemo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemo,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.DeleteMemoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RenameMemoTag': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameMemoTag,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.RenameMemoTagRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteMemoTag': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemoTag,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.DeleteMemoTagRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetMemoAttachments': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMemoAttachments,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.SetMemoAttachmentsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListMemoAttachments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemoAttachments,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoAttachmentsRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoAttachmentsResponse.SerializeToString,
            ),
            'SetMemoRelations': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMemoRelations,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.SetMemoRelationsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListMemoRelations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemoRelations,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoRelationsRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoRelationsResponse.SerializeToString,
            ),
            'CreateMemoComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMemoComment,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.CreateMemoCommentRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.Memo.SerializeToString,
            ),
            'ListMemoComments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemoComments,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoCommentsRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoCommentsResponse.SerializeToString,
            ),
            'ListMemoReactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemoReactions,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.ListMemoReactionsRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.ListMemoReactionsResponse.SerializeToString,
            ),
            'UpsertMemoReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertMemoReaction,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.UpsertMemoReactionRequest.FromString,
                    response_serializer=api_dot_v1_dot_memo__service__pb2.Reaction.SerializeToString,
            ),
            'DeleteMemoReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemoReaction,
                    request_deserializer=api_dot_v1_dot_memo__service__pb2.DeleteMemoReactionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.MemoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.MemoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/CreateMemo',
            api_dot_v1_dot_memo__service__pb2.CreateMemoRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.Memo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/ListMemos',
            api_dot_v1_dot_memo__service__pb2.ListMemosRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.ListMemosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/GetMemo',
            api_dot_v1_dot_memo__service__pb2.GetMemoRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.Memo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/UpdateMemo',
            api_dot_v1_dot_memo__service__pb2.UpdateMemoRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.Memo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/DeleteMemo',
            api_dot_v1_dot_memo__service__pb2.DeleteMemoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameMemoTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/RenameMemoTag',
            api_dot_v1_dot_memo__service__pb2.RenameMemoTagRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemoTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/DeleteMemoTag',
            api_dot_v1_dot_memo__service__pb2.DeleteMemoTagRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMemoAttachments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/SetMemoAttachments',
            api_dot_v1_dot_memo__service__pb2.SetMemoAttachmentsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemoAttachments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/ListMemoAttachments',
            api_dot_v1_dot_memo__service__pb2.ListMemoAttachmentsRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.ListMemoAttachmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMemoRelations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/SetMemoRelations',
            api_dot_v1_dot_memo__service__pb2.SetMemoRelationsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemoRelations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/ListMemoRelations',
            api_dot_v1_dot_memo__service__pb2.ListMemoRelationsRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.ListMemoRelationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMemoComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/CreateMemoComment',
            api_dot_v1_dot_memo__service__pb2.CreateMemoCommentRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.Memo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemoComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/ListMemoComments',
            api_dot_v1_dot_memo__service__pb2.ListMemoCommentsRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.ListMemoCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemoReactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/ListMemoReactions',
            api_dot_v1_dot_memo__service__pb2.ListMemoReactionsRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.ListMemoReactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertMemoReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/UpsertMemoReaction',
            api_dot_v1_dot_memo__service__pb2.UpsertMemoReactionRequest.SerializeToString,
            api_dot_v1_dot_memo__service__pb2.Reaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemoReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.MemoService/DeleteMemoReaction',
            api_dot_v1_dot_memo__service__pb2.DeleteMemoReactionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
