# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import shortcut_service_pb2 as api_dot_v1_dot_shortcut__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/shortcut_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShortcutServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListShortcuts = channel.unary_unary(
                '/memos.api.v1.ShortcutService/ListShortcuts',
                request_serializer=api_dot_v1_dot_shortcut__service__pb2.ListShortcutsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_shortcut__service__pb2.ListShortcutsResponse.FromString,
                _registered_method=True)
        self.GetShortcut = channel.unary_unary(
                '/memos.api.v1.ShortcutService/GetShortcut',
                request_serializer=api_dot_v1_dot_shortcut__service__pb2.GetShortcutRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_shortcut__service__pb2.Shortcut.FromString,
                _registered_method=True)
        self.CreateShortcut = channel.unary_unary(
                '/memos.api.v1.ShortcutService/CreateShortcut',
                request_serializer=api_dot_v1_dot_shortcut__service__pb2.CreateShortcutRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_shortcut__service__pb2.Shortcut.FromString,
                _registered_method=True)
        self.UpdateShortcut = channel.unary_unary(
                '/memos.api.v1.ShortcutService/UpdateShortcut',
                request_serializer=api_dot_v1_dot_shortcut__service__pb2.UpdateShortcutRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_shortcut__service__pb2.Shortcut.FromString,
                _registered_method=True)
        self.DeleteShortcut = channel.unary_unary(
                '/memos.api.v1.ShortcutService/DeleteShortcut',
                request_serializer=api_dot_v1_dot_shortcut__service__pb2.DeleteShortcutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ShortcutServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListShortcuts(self, request, context):
        """ListShortcuts returns a list of shortcuts for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShortcut(self, request, context):
        """GetShortcut gets a shortcut by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateShortcut(self, request, context):
        """CreateShortcut creates a new shortcut for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShortcut(self, request, context):
        """UpdateShortcut updates a shortcut for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShortcut(self, request, context):
        """DeleteShortcut deletes a shortcut for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShortcutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListShortcuts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShortcuts,
                    request_deserializer=api_dot_v1_dot_shortcut__service__pb2.ListShortcutsRequest.FromString,
                    response_serializer=api_dot_v1_dot_shortcut__service__pb2.ListShortcutsResponse.SerializeToString,
            ),
            'GetShortcut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShortcut,
                    request_deserializer=api_dot_v1_dot_shortcut__service__pb2.GetShortcutRequest.FromString,
                    response_serializer=api_dot_v1_dot_shortcut__service__pb2.Shortcut.SerializeToString,
            ),
            'CreateShortcut': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShortcut,
                    request_deserializer=api_dot_v1_dot_shortcut__service__pb2.CreateShortcutRequest.FromString,
                    response_serializer=api_dot_v1_dot_shortcut__service__pb2.Shortcut.SerializeToString,
            ),
            'UpdateShortcut': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShortcut,
                    request_deserializer=api_dot_v1_dot_shortcut__service__pb2.UpdateShortcutRequest.FromString,
                    response_serializer=api_dot_v1_dot_shortcut__service__pb2.Shortcut.SerializeToString,
            ),
            'DeleteShortcut': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShortcut,
                    request_deserializer=api_dot_v1_dot_shortcut__service__pb2.DeleteShortcutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.ShortcutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.ShortcutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShortcutService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListShortcuts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.ShortcutService/ListShortcuts',
            api_dot_v1_dot_shortcut__service__pb2.ListShortcutsRequest.SerializeToString,
            api_dot_v1_dot_shortcut__service__pb2.ListShortcutsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShortcut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.ShortcutService/GetShortcut',
            api_dot_v1_dot_shortcut__service__pb2.GetShortcutRequest.SerializeToString,
            api_dot_v1_dot_shortcut__service__pb2.Shortcut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateShortcut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.ShortcutService/CreateShortcut',
            api_dot_v1_dot_shortcut__service__pb2.CreateShortcutRequest.SerializeToString,
            api_dot_v1_dot_shortcut__service__pb2.Shortcut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateShortcut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.ShortcutService/UpdateShortcut',
            api_dot_v1_dot_shortcut__service__pb2.UpdateShortcutRequest.SerializeToString,
            api_dot_v1_dot_shortcut__service__pb2.Shortcut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteShortcut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.ShortcutService/DeleteShortcut',
            api_dot_v1_dot_shortcut__service__pb2.DeleteShortcutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
