# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import user_service_pb2 as api_dot_v1_dot_user__service__pb2
from google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/memos.api.v1.UserService/ListUsers',
                request_serializer=api_dot_v1_dot_user__service__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/memos.api.v1.UserService/GetUser',
                request_serializer=api_dot_v1_dot_user__service__pb2.GetUserRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/memos.api.v1.UserService/CreateUser',
                request_serializer=api_dot_v1_dot_user__service__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/memos.api.v1.UserService/UpdateUser',
                request_serializer=api_dot_v1_dot_user__service__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/memos.api.v1.UserService/DeleteUser',
                request_serializer=api_dot_v1_dot_user__service__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetUserAvatar = channel.unary_unary(
                '/memos.api.v1.UserService/GetUserAvatar',
                request_serializer=api_dot_v1_dot_user__service__pb2.GetUserAvatarRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
                _registered_method=True)
        self.ListAllUserStats = channel.unary_unary(
                '/memos.api.v1.UserService/ListAllUserStats',
                request_serializer=api_dot_v1_dot_user__service__pb2.ListAllUserStatsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.ListAllUserStatsResponse.FromString,
                _registered_method=True)
        self.GetUserStats = channel.unary_unary(
                '/memos.api.v1.UserService/GetUserStats',
                request_serializer=api_dot_v1_dot_user__service__pb2.GetUserStatsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.UserStats.FromString,
                _registered_method=True)
        self.GetUserSetting = channel.unary_unary(
                '/memos.api.v1.UserService/GetUserSetting',
                request_serializer=api_dot_v1_dot_user__service__pb2.GetUserSettingRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.UserSetting.FromString,
                _registered_method=True)
        self.UpdateUserSetting = channel.unary_unary(
                '/memos.api.v1.UserService/UpdateUserSetting',
                request_serializer=api_dot_v1_dot_user__service__pb2.UpdateUserSettingRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.UserSetting.FromString,
                _registered_method=True)
        self.ListUserSettings = channel.unary_unary(
                '/memos.api.v1.UserService/ListUserSettings',
                request_serializer=api_dot_v1_dot_user__service__pb2.ListUserSettingsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.ListUserSettingsResponse.FromString,
                _registered_method=True)
        self.ListUserAccessTokens = channel.unary_unary(
                '/memos.api.v1.UserService/ListUserAccessTokens',
                request_serializer=api_dot_v1_dot_user__service__pb2.ListUserAccessTokensRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.ListUserAccessTokensResponse.FromString,
                _registered_method=True)
        self.CreateUserAccessToken = channel.unary_unary(
                '/memos.api.v1.UserService/CreateUserAccessToken',
                request_serializer=api_dot_v1_dot_user__service__pb2.CreateUserAccessTokenRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.UserAccessToken.FromString,
                _registered_method=True)
        self.DeleteUserAccessToken = channel.unary_unary(
                '/memos.api.v1.UserService/DeleteUserAccessToken',
                request_serializer=api_dot_v1_dot_user__service__pb2.DeleteUserAccessTokenRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListUserSessions = channel.unary_unary(
                '/memos.api.v1.UserService/ListUserSessions',
                request_serializer=api_dot_v1_dot_user__service__pb2.ListUserSessionsRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.ListUserSessionsResponse.FromString,
                _registered_method=True)
        self.RevokeUserSession = channel.unary_unary(
                '/memos.api.v1.UserService/RevokeUserSession',
                request_serializer=api_dot_v1_dot_user__service__pb2.RevokeUserSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListUserWebhooks = channel.unary_unary(
                '/memos.api.v1.UserService/ListUserWebhooks',
                request_serializer=api_dot_v1_dot_user__service__pb2.ListUserWebhooksRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.ListUserWebhooksResponse.FromString,
                _registered_method=True)
        self.CreateUserWebhook = channel.unary_unary(
                '/memos.api.v1.UserService/CreateUserWebhook',
                request_serializer=api_dot_v1_dot_user__service__pb2.CreateUserWebhookRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.UserWebhook.FromString,
                _registered_method=True)
        self.UpdateUserWebhook = channel.unary_unary(
                '/memos.api.v1.UserService/UpdateUserWebhook',
                request_serializer=api_dot_v1_dot_user__service__pb2.UpdateUserWebhookRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_user__service__pb2.UserWebhook.FromString,
                _registered_method=True)
        self.DeleteUserWebhook = channel.unary_unary(
                '/memos.api.v1.UserService/DeleteUserWebhook',
                request_serializer=api_dot_v1_dot_user__service__pb2.DeleteUserWebhookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """ListUsers returns a list of users.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """GetUser gets a user by ID or username.
        Supports both numeric IDs and username strings:
        - users/{id}       (e.g., users/101)
        - users/{username} (e.g., users/steven)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """CreateUser creates a new user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """UpdateUser updates a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """DeleteUser deletes a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAvatar(self, request, context):
        """GetUserAvatar gets the avatar of a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllUserStats(self, request, context):
        """ListAllUserStats returns statistics for all users.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserStats(self, request, context):
        """GetUserStats returns statistics for a specific user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSetting(self, request, context):
        """GetUserSetting returns the user setting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserSetting(self, request, context):
        """UpdateUserSetting updates the user setting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserSettings(self, request, context):
        """ListUserSettings returns a list of user settings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserAccessTokens(self, request, context):
        """ListUserAccessTokens returns a list of access tokens for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserAccessToken(self, request, context):
        """CreateUserAccessToken creates a new access token for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserAccessToken(self, request, context):
        """DeleteUserAccessToken deletes an access token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserSessions(self, request, context):
        """ListUserSessions returns a list of active sessions for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeUserSession(self, request, context):
        """RevokeUserSession revokes a specific session for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserWebhooks(self, request, context):
        """ListUserWebhooks returns a list of webhooks for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserWebhook(self, request, context):
        """CreateUserWebhook creates a new webhook for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserWebhook(self, request, context):
        """UpdateUserWebhook updates an existing webhook for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserWebhook(self, request, context):
        """DeleteUserWebhook deletes a webhook for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.ListUsersRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.ListUsersResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.GetUserRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.CreateUserRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.UpdateUserRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.DeleteUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUserAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAvatar,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.GetUserAvatarRequest.FromString,
                    response_serializer=google_dot_api_dot_httpbody__pb2.HttpBody.SerializeToString,
            ),
            'ListAllUserStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllUserStats,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.ListAllUserStatsRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.ListAllUserStatsResponse.SerializeToString,
            ),
            'GetUserStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserStats,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.GetUserStatsRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.UserStats.SerializeToString,
            ),
            'GetUserSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSetting,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.GetUserSettingRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.UserSetting.SerializeToString,
            ),
            'UpdateUserSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserSetting,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.UpdateUserSettingRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.UserSetting.SerializeToString,
            ),
            'ListUserSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserSettings,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.ListUserSettingsRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.ListUserSettingsResponse.SerializeToString,
            ),
            'ListUserAccessTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserAccessTokens,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.ListUserAccessTokensRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.ListUserAccessTokensResponse.SerializeToString,
            ),
            'CreateUserAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserAccessToken,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.CreateUserAccessTokenRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.UserAccessToken.SerializeToString,
            ),
            'DeleteUserAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserAccessToken,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.DeleteUserAccessTokenRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListUserSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserSessions,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.ListUserSessionsRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.ListUserSessionsResponse.SerializeToString,
            ),
            'RevokeUserSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeUserSession,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.RevokeUserSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListUserWebhooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserWebhooks,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.ListUserWebhooksRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.ListUserWebhooksResponse.SerializeToString,
            ),
            'CreateUserWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserWebhook,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.CreateUserWebhookRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.UserWebhook.SerializeToString,
            ),
            'UpdateUserWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserWebhook,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.UpdateUserWebhookRequest.FromString,
                    response_serializer=api_dot_v1_dot_user__service__pb2.UserWebhook.SerializeToString,
            ),
            'DeleteUserWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserWebhook,
                    request_deserializer=api_dot_v1_dot_user__service__pb2.DeleteUserWebhookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/ListUsers',
            api_dot_v1_dot_user__service__pb2.ListUsersRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/GetUser',
            api_dot_v1_dot_user__service__pb2.GetUserRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/CreateUser',
            api_dot_v1_dot_user__service__pb2.CreateUserRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/UpdateUser',
            api_dot_v1_dot_user__service__pb2.UpdateUserRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/DeleteUser',
            api_dot_v1_dot_user__service__pb2.DeleteUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/GetUserAvatar',
            api_dot_v1_dot_user__service__pb2.GetUserAvatarRequest.SerializeToString,
            google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllUserStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/ListAllUserStats',
            api_dot_v1_dot_user__service__pb2.ListAllUserStatsRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.ListAllUserStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/GetUserStats',
            api_dot_v1_dot_user__service__pb2.GetUserStatsRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.UserStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/GetUserSetting',
            api_dot_v1_dot_user__service__pb2.GetUserSettingRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.UserSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/UpdateUserSetting',
            api_dot_v1_dot_user__service__pb2.UpdateUserSettingRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.UserSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/ListUserSettings',
            api_dot_v1_dot_user__service__pb2.ListUserSettingsRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.ListUserSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserAccessTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/ListUserAccessTokens',
            api_dot_v1_dot_user__service__pb2.ListUserAccessTokensRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.ListUserAccessTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/CreateUserAccessToken',
            api_dot_v1_dot_user__service__pb2.CreateUserAccessTokenRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.UserAccessToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/DeleteUserAccessToken',
            api_dot_v1_dot_user__service__pb2.DeleteUserAccessTokenRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/ListUserSessions',
            api_dot_v1_dot_user__service__pb2.ListUserSessionsRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.ListUserSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeUserSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/RevokeUserSession',
            api_dot_v1_dot_user__service__pb2.RevokeUserSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserWebhooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/ListUserWebhooks',
            api_dot_v1_dot_user__service__pb2.ListUserWebhooksRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.ListUserWebhooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/CreateUserWebhook',
            api_dot_v1_dot_user__service__pb2.CreateUserWebhookRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.UserWebhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/UpdateUserWebhook',
            api_dot_v1_dot_user__service__pb2.UpdateUserWebhookRequest.SerializeToString,
            api_dot_v1_dot_user__service__pb2.UserWebhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.UserService/DeleteUserWebhook',
            api_dot_v1_dot_user__service__pb2.DeleteUserWebhookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
