# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_memos.api.v1 import workspace_service_pb2 as api_dot_v1_dot_workspace__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/workspace_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkspaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorkspaceProfile = channel.unary_unary(
                '/memos.api.v1.WorkspaceService/GetWorkspaceProfile',
                request_serializer=api_dot_v1_dot_workspace__service__pb2.GetWorkspaceProfileRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_workspace__service__pb2.WorkspaceProfile.FromString,
                _registered_method=True)
        self.GetWorkspaceSetting = channel.unary_unary(
                '/memos.api.v1.WorkspaceService/GetWorkspaceSetting',
                request_serializer=api_dot_v1_dot_workspace__service__pb2.GetWorkspaceSettingRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_workspace__service__pb2.WorkspaceSetting.FromString,
                _registered_method=True)
        self.UpdateWorkspaceSetting = channel.unary_unary(
                '/memos.api.v1.WorkspaceService/UpdateWorkspaceSetting',
                request_serializer=api_dot_v1_dot_workspace__service__pb2.UpdateWorkspaceSettingRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_workspace__service__pb2.WorkspaceSetting.FromString,
                _registered_method=True)


class WorkspaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWorkspaceProfile(self, request, context):
        """Gets the workspace profile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspaceSetting(self, request, context):
        """Gets a workspace setting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkspaceSetting(self, request, context):
        """Updates a workspace setting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorkspaceProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspaceProfile,
                    request_deserializer=api_dot_v1_dot_workspace__service__pb2.GetWorkspaceProfileRequest.FromString,
                    response_serializer=api_dot_v1_dot_workspace__service__pb2.WorkspaceProfile.SerializeToString,
            ),
            'GetWorkspaceSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspaceSetting,
                    request_deserializer=api_dot_v1_dot_workspace__service__pb2.GetWorkspaceSettingRequest.FromString,
                    response_serializer=api_dot_v1_dot_workspace__service__pb2.WorkspaceSetting.SerializeToString,
            ),
            'UpdateWorkspaceSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkspaceSetting,
                    request_deserializer=api_dot_v1_dot_workspace__service__pb2.UpdateWorkspaceSettingRequest.FromString,
                    response_serializer=api_dot_v1_dot_workspace__service__pb2.WorkspaceSetting.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memos.api.v1.WorkspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memos.api.v1.WorkspaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkspaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWorkspaceProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.WorkspaceService/GetWorkspaceProfile',
            api_dot_v1_dot_workspace__service__pb2.GetWorkspaceProfileRequest.SerializeToString,
            api_dot_v1_dot_workspace__service__pb2.WorkspaceProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspaceSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.WorkspaceService/GetWorkspaceSetting',
            api_dot_v1_dot_workspace__service__pb2.GetWorkspaceSettingRequest.SerializeToString,
            api_dot_v1_dot_workspace__service__pb2.WorkspaceSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkspaceSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memos.api.v1.WorkspaceService/UpdateWorkspaceSetting',
            api_dot_v1_dot_workspace__service__pb2.UpdateWorkspaceSettingRequest.SerializeToString,
            api_dot_v1_dot_workspace__service__pb2.WorkspaceSetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
